### ISSUE TITLE
<Windows> dotnet run seed gives DataBase is null exception

### ISSUE THREAD

**Issue by PatrickH-H** [ITU-BDSA23-GROUP22/Chirp#70]
Currently, when running "dotnet run seed" for windows, the code meant to grab the ASPNET_CORE environment doesn't work 
(Chirp.Migration > DbContextFactory line 18)

Succes Criteria:
Fix the code so it uses the current ASPNET_CORE environment path so we don't have to enter it manually

**Comment by MarcusKofoedKirkegaard** [comment]
This is not necessary with the new database configurations
