### ISSUE TITLE
When logging in using GitHub, if the user has private email on GitHub, we will not be able to fetch that Email. Instead, we want to use ID instead of Email as Author ID in Database.

### ISSUE THREAD

**Issue by PatrickH-H** [ITU-BDSA23-GROUP22/Chirp#73]
As a Developer, we want to have access to a mail otherwise some of our features dont work (and we want to have emails as unique identifier to a user). This is not possible if their GitHub mail is private, therefore we want to create a temporrary email

Success criteria:
Give the user a temporary email if we don't have access to theirs.

**Comment by MarcusKofoedKirkegaard** [comment]
As there is no requirement for features or functionality with email in the application, we have adjusted the issue to remove email entirely from the application, to be replaced by ID.
